--- 
- hosts: 127.0.0.1
  vars: 
    apche_port : 443
   
  tasks:
  - name: Install the apache
    package: 
      name: "{{packages}}"
      state: present

  - name: Ensure the installed service is enabled and running
    service:
      name: "{{service}}"
      state: started
      enabled: true
  - name: Index .html filee
    copy:
      src: ./files/index.html
      dest: /var/www/html/index.html
    register: configfile
  - name: apache restart
    when: configfile.changed
    service: 
      name: "{{service}}"
      state: restarted


